import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
const mada = localFont({
  src: "./assests/fonts/Mada-VariableFont_wght.ttf",
  variable: "--font-mada",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mada.variable}`}>
        {children}
      </body>
    </html>
  );
}
