import { FC } from "react";
import Text from "@/app/components/text";
import Navbar from "@/app/components/navbar";
import Link from "next/link";
import MoreQuestion from "@/app/components/more question";
import Footer from "@/app/components/footer";
import ContentBox from "@/app/components/contentBox";
import PressLegalBanner from "@/app/components/PressLegalBanner";

const TermsAndConditions:FC = ()=>{
    return(
<main className="termsConditions">
    <Navbar/>
    <PressLegalBanner heading="Terms & Conditions" text="Please read this agreement carefully before using this service." />
    <ContentBox style={{lineHeight:"36px"}} mt={9}>
        <Text className="heading_1" fontSize="60px" fontWeight="700">Ezsignature Terms of Use</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">Last Modified: December 12, 2022</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">The following are the terms and conditions for use of Ezsignature GmbH’s (“Ezsignature (formerly eversign)”, “we”, “us”, and “our”) website and 
              services (the “Services”). Please read them carefully. By using the Services or clicking on the “I agree” button, you agree to be bound by all 
              of the Terms set out in these Terms of Use (the &quot;Terms&quot;). If you do not agree to the Terms do not use the Services. </Text>
        <Text fontSize="34px" marginTop={60} marginBottom={10} fontWeight="700">1. Your Account</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">An Ezsignature account gives you access to the Services and functionality that we may establish and maintain from time to time. We may maintain 
              different types of accounts which allow users to work within different features, and file number limitations.
              Users are solely responsible for the activity that occurs on their account and must keep their account password confidential and secure. You shall 
              notify Ezsignature immediately of any unauthorized use of your account. Ezsignature will not be liable for any loss that you may incur as a result of 
              someone else using your password or account. However, you may be held liable for losses incurred by Ezsignature or another party due to someone 
              else using your account or password. You may not use anyone else’s account at any time. In the event that access to your account is suspended or 
              terminated, Ezsignature shall not be liable to you or any third party for suspension or termination of your account, unless prohibited by 
              applicable law.</Text>
        <Text fontSize="34px" marginTop={60} marginBottom={10} fontWeight="700">2. USE OF THE SERVICE AND USER CONDUCT</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">Any actual or attempted commercial use of any Services by you&apos; such as charging or attempting to charge third parties a fee to sign the third parties&apos; 
            documents by running them through the Services or reselling Services accounts to others, is expressly prohibited. You may use the Services for 
            your personal needs or your internal business needs. For clarity, ‘internal business needs’ means the use of the Services for the benefit of your 
            organization&apos;s internal operations and work environment (which includes circulating your business documents or sales contracts for signature). 
            You agree that your use of the Services will at all times comply with all applicable local, provincial, state, federal, national and international laws 
            and regulations, and that you are solely responsible for all acts or omissions that occur under your account, including the content of documents 
            you submit to the Services. Ezsignature is not obligated to provide any technical support for your use of the Services. The terms 
            of our Privacy Policy from time to time are incorporated into these Terms by reference and apply to the Services. To the extent any of your personal 
            data is processed by Ezsignature on your behalf, our<Link href="#" style={{color:"#21D0B3"}}> Data Processing Agreement</Link> will apply.</Text>
        <Text fontSize="34px" marginTop={60} marginBottom={10} fontWeight="700">i. Restrictions on Use</Text>    
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">You agree not to attempt to decompile, disassemble, modify, reverse engineer or translate the software used within the Services or otherwise attempt to learn the source code of any software or Services we provide to you. You are not authorized to alter, modify, copy, edit, format, or create derivative works of any technology used to provide the Services.</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">Furthermore, the following actions are prohibited while using the Services or functionality we provide to you as part of the Services:</Text>
        <ul style={{fontSize:"22px",fontWeight:'600'}}>
        <li>enabling or allowing others to use the Services, software, or content using your account information;</li>
        <li>Hosting or streaming the Services, software or functionality used to provide the Services;</li>
        <li>using the functionality or software included in the Services to construct any kind of database;</li>
        <li>circumventing any access or use restrictions put into place to prevent certain uses of the Services;</li>
        <li>uploading or transmitting any content that is unlawful, defamatory, obscene, pornographic, harassing, threatening, harmful, abusive,inflammatory, or otherwise objectionable;</li>
        <li>uploading or transmitting any content that would constitute or encourage a criminal offence, violate the rights of any party, or that would otherwise create liability or violate any local, provincial, state, national, or international law;</li>
        <li>sharing content or engaging in behavior that violates anyone’s Intellectual Property Rights (“Intellectual Property Rights” means copyright, moral rights, trademark, trade dress, patent, trade secret, unfair competition, right of privacy, right of publicity, and any other proprietary rights);</li>
        <li>attempting to disable, impair, or destroy the Services, software, or hardware;</li>
        <li>engaging in chain letters, junk mails, pyramid schemes, spamming, or other unsolicited messages;</li>
        <li>placing advertisements of any products or services in the Services except with our prior written consent;</li>
        <li>using any data mining or similar data gathering and extraction methods in connection with the Services;</li>
        <li>framing or utilizing framing techniques to enclose any Xodo Sign (formerly eversign) trademark, logo or other proprietary information (including the images found on the Services, the content of any text or the layout/design of any page or form contained on a page) without Xodo Sign (formerly eversign)&apos;s express written consent;</li>
        <li>encrypting or protecting files in countries where this is prohibited;</li>
        <li>running any vulnerability or authentication tests.</li>
        </ul>
        <Text fontSize="34px" marginTop={60} marginBottom={10} fontWeight="700">ii. Age Restrictions</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">You may only use the Services if you are 18 years of age (or the age of majority in your home jurisdiction to lawfully enter into and form contracts in accordance with applicable local laws) or older.</Text>
        <Text fontSize="34px" marginTop={60} marginBottom={10} fontWeight="700">3. DISCLAIMER AND LIMITATION OF LIABILITY</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">To the maximum extent permitted by applicable law, the Services are provided &quot;as is&quot; and &quot;as available&quot; without any express or implied warranty or condition of any kind including, but not limited to, warranties or conditions of merchantable quality, merchantability, durability, noninfringement of Intellectual Property Rights, fitness for any particular purpose, that stored documents will be preserved without loss or that the Services will be uninterrupted, timely, or error-free, or that defects will be corrected. While Ezsignature attempts to ensure your access and use of the Services is safe, Ezsignature cannot and does not represent or warrant that the Services or its server(s) are free of viruses or other harmful components. Certain jurisdictions do not permit the disclaimers in this paragraph, so they may not apply to you. For example, these disclaimers do not override the legal protections (including any statutory warranties) that are granted to consumers by the laws of the EU.</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">Ezsignature does not exclude or limit its liability to you where it would be illegal to do so—this includes any liability for Ezsignature fraud or fraudulent misrepresentation in providing the Services. In countries where the exclusions below are not allowed, we are responsible to you only for damages that are a reasonably foreseeable result of our failure to use reasonable care or our breach of the Terms. This paragraph does not affect consumer rights that cannot be waived or limited by any contract.</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">In countries where exclusions or limitations of liability are allowed, in no event shall Ezsignature or its officers, directors, employees, contractors, suppliers, and agents (&quot;Ezsignature parties&quot;), be liable for any damages whatsoever (including, without limitation, for any direct, special, indirect, consequential, incidental, punitive or exemplary damages, or any other damages of any kind, including but not limited to, loss of use, loss of profits, business interruption, or loss of information), arising out of the use of, inability to use or reliance upon the Services, even if Ezsignature has been advised of the possibility of such damages.</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">Independent of, severable from and to be enforced independently of any other enforceable or unenforceable provision of the Terms, in no event will Ezsignature parties be liable to you (including liability to person or persons whose claim or claims are based on or derived from a right or rights claimed by you), with respect to any and all claims at any and all times arising from or related to the use of the Services or the Terms, that exceeds the amount you have paid for the use of the Services during the previous 12 month period, or USD $10.00, whichever is greater. This provision does not apply to EU consumers where prohibited by applicable law.</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">The foregoing limitations of liability and exclusion of certain damages will apply to all causes of action, regardless of the cause of action and whether based on warranty, contract, tort (including negligence) or any other legal theory, to the extent permitted by applicable law and regardless of the success or effectiveness of other remedies.</Text>
        <Text fontSize="34px" marginTop={60} marginBottom={10} fontWeight="700">4. INDEMNIFICATION</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">You agree to indemnify and hold Ezsignature, its parents, subsidiaries, affiliates, officers and employees, harmless of and from any claim, demand, or damage, including reasonable attorneys&apos; fees, asserted by any third party due to or arising out of your content or your use of or conduct with regard to the Services.</Text>
        <Text fontSize="34px" marginTop={60} marginBottom={10} fontWeight="700">5. MODIFICATION AND TERMINATION</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">To the extent permitted under applicable law, Ezsignature reserves the right to discontinue offering all or part of the Services or to modify the Services at any time, without any liability to you or anyone else, in its sole discretion. For changes to paid offerings that, in Ezsignature reasonable discretion, result in a material diminishment of value to you, we will make reasonable commercial efforts to notify you of such modification or discontinuation. If you are dissatisfied with any aspect of the Services at any time, your sole and exclusive remedy is to cease using the Services. Ezsignature, in its sole and exclusive discretion, may suspend or terminate your access to the Services if: (a) you violate the Terms either in letter or in spirit; (b) If you fail to make timely payments of fees for the Services; (c) if we are required to do so by law (for example, if providing software to a specific region becomes unlawful); and (d) if we choose to discontinue the Services, in whole or in part (such as if it becomes impractical for us to provide Services in your jurisdiction). If you are a user of a free account, Ezsignature may terminate the Services with or without cause upon 30 days’ notice to you. Upon termination of the Services, your right to use the Services immediately ceases. If we discontinue any Services in its entirety, then we will provide you with a pro rata refund for any unused fees for the discontinued Services that you may have prepaid. Termination of your account shall not relieve you of any obligation or liability accruing prior to such termination, nor preclude Ezsignature from pursuing all rights and remedies it may have under these Terms, at law or in equity, with respect to breach of these Terms.</Text>
        <Text fontSize="34px" marginTop={60} marginBottom={10} fontWeight="700">6. CHANGES TO TERMS</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">Ezsignature reserves the right to change the Terms at any time and to notify you by posting an updated version of the Terms on the website and any other reasonable means as Ezsignature deems appropriate. If you do not agree to these changes, then you must stop using the Services. If you do not stop using the Services then your use of the Services will continue under the changed terms. Your continued use of the Services constitutes your agreement to be bound by all of these Terms as amended by us from time to time.</Text>
        <Text fontSize="34px" marginTop={60} marginBottom={10} fontWeight="700">7. SANCTION AND EXPORT RESTRICTIONS</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">Any use of the Services shall be in compliance with all relevant international, U.N., Canada, USA or EU sales, export or import restrictions and regulations and you agree to comply with them. You represent and warrant that you are not located in a country that is subject to embargo, or that has been designated by the United States as a “terrorist supporting” country; and that you are not listed in any Canadian, United States or EU sanction list of prohibited or restricted parties and you comply with relevant sanctions and embargos.</Text>
        <Text fontSize="34px" marginTop={60} marginBottom={10} fontWeight="700">8. GOVERNING LAW</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">These Terms will be governed by and interpreted in accordance with the laws (procedural and substantive) of California as if made and performed by and between parties situate in such jurisdiction and without regard to any conflict of laws doctrine. The application of the United Nations Convention on Contracts for the International Sale of Goods will not apply to any part of any transaction which may result from these Terms and the same is strictly excluded from these Terms. You and Ezsignature submit to the exclusive jurisdiction of the courts of Santa Clara County, California and waive any objection as to venue in such courts. Notwithstanding any of these Terms, Ezsignature may apply to a court of competent jurisdiction for interim or injunctive relief pending resolution of the dispute. Notwithstanding the foregoing, some countries (including those in the EU) have laws that require agreements to be governed by the local laws of the consumer’s country. This section does not override such laws.</Text>
        <Text fontSize="34px" marginTop={60} marginBottom={10} fontWeight="700">9. BILLING AND RENEWAL</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">If you decide to purchase a paid subscription to any of the Services (or any particular features of the Services), you will be charged the stated fee in advance on a monthly or yearly basis or some other recurring interval disclosed to you prior to your purchase. We may change the price for the paid subscription, including recurring subscription fees (for periods not yet paid) from time to time and will communicate any price changes to you at least 30 days in advance. Such notice may be provided by an email to you or in the form of an announcement on the Service. Price changes will take effect at the start of the next subscription period following the date of the price change. Subject to applicable law, you accept the new price by continuing to use the Services after the price change takes effect. If you do not agree with a price change, you may reject the change by unsubscribing from the paid subscription prior to the price change going into effect.</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">We will automatically bill the subscription fee to your plan, price and payment method selected until your subscription is cancelled or terminated. If you do not terminate your subscription, it will be automatically renewed. You and Ezsignature may cancel or terminate your subscription at any time. Any cancellation will take place from the next billing period, i.e. any cancellation will only cancel future billings. We do not provide refunds except in cases requested by mandatory law or where otherwise explicitly communicated to you.</Text>
        <Text fontSize="34px" marginTop={60} marginBottom={10} fontWeight="700">10. OWNERSHIP OF IP</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">We (and our licensors) remain the sole owner of all right, title, and interest relating to or embodied in the Services, including all Intellectual Property Rights related thereto. We reserve all rights not granted under these Terms. We may use feedback you provide in connection with your use of the Services as part of our business operations without any obligation or restriction of any kind. Further, all graphics, logos, domain names, trademarks and trade names relating to the Services (collectively, the “Marks”) are the property of Ezsignature and its licensors. Ezsignature and its licensors retain all rights, title and interest, including all Intellectual Property Rights, in and to the Marks. You are prohibited from using any of the Marks.</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">We do not claim any ownership rights to your content.</Text>
        <Text fontSize="34px" marginTop={60} marginBottom={10} fontWeight="700">11. USE OF E-SIGNATURE FEATURES</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">Certain types of documents or agreements may be excluded from general electronic signature laws (for example, wills, trusts, court orders, or family law matters), or may have specific regulations that are applicable to them. You are solely responsible for ensuring that the documents you use with the Services are appropriate for electronic signatures, and Ezsignature is not responsible or liable for any such determination or use.</Text>
        <Text fontSize="22px" margin={"25px 0"} fontWeight="600">Consumer protection laws or regulations in some jurisdictions may impose specific requirements for electronic transactions involving consumers; you are solely responsible for ensuring that you comply with all such laws or regulations and Ezsignature has no obligations to make such determination or assist with fulfilling any such requirements.</Text>
        <Text fontSize="34px" marginTop={60} marginBottom={10} fontWeight="700">12. FILE STORAGE</Text>
        <Text fontSize="22px" margin={"25px 0 0 0"} fontWeight="600">If file storage is provided, the following terms will apply:</Text>
        <ul style={{fontSize:"22px",fontWeight:'600',marginTop:"0px"}}>
            <li>Xodo Sign (formerly eversign) uses TLS encryption. Xodo Sign (formerly eversign) shall have in place and shall comply with documented written policies and procedures, periodically reviewed, covering the administrative and technical safeguards in place and relevant to the access, use, loss, alteration, disclosure, storage, destruction and control of information. Such policies and procedures will include encryption of data in storage and in motion over public networks, virus detection and firewall utilization. Furthermore, users’ information is stored with logical separation from information of other customers.</li>
           <li>Xodo Sign (formerly eversign) shall not access users&apos; stored files, except to respond to service or technical problems or at users&apos; request or except as compelled by law.</li>
           <li>In the event of unauthorized access to your files, Xodo Sign (formerly eversign) will endeavour to promptly notify you of such unauthorized access.</li>
           <li>Upon request made within 30 days after the effective date of termination of your use of your account, Xodo Sign (formerly eversign) will make available to you for download your files in their native format. After such 30-day period, Xodo Sign (formerly eversign) shall have no obligation to maintain or provide any files and shall thereafter, unless legally prohibited, delete all files in its systems or otherwise in its possession or under its control.</li>
        </ul>
        <Text fontSize="34px" marginTop={60} marginBottom={10} fontWeight="700">13. MISCELLANEOUS</Text>
        <ol style={{fontSize:"22px",fontWeight:'600',marginTop:"0px"}}>
            <li>Event Outside Our Control. We will not be liable or responsible for any failure to perform, or delay in performance of, any of our obligations under these Terms that is caused by any act or event beyond our reasonable control, including failure of public or private telecommunications networks.</li>
            <li>Assignment. We may assign or transfer our rights and obligations under these Terms to another organisation without consent. You may only assign or transfer your rights or obligations under these Terms to another person if we agree in writing.</li>
            <li>Waiver and Severability. The failure of Xodo Sign (formerly eversign) to enforce any right or provision of these Terms will not be deemed a waiver of such right or provision. In the event that any provision of these Terms is held to be invalid or unenforceable, the remaining provisions of these Terms will remain in full force and effect.</li>
            <li>Entire Agreement. hese Terms are the entire agreement between Xodo Sign (formerly eversign) and you regarding the use of the Services, and these Terms supersede and replace any prior agreements between Xodo Sign (formerly eversign) and you regarding the same. Subject to the provisions set forth in Section 6 (Changes to Terms), no amendment to or modification of these Terms will be binding unless in writing, signed by an authorized senior executive of Xodo Sign (formerly eversign), and expressly referring to these Terms.</li>
            <li>Interpretation. The headings to, and the division of these Terms into Sections, Subsections, Paragraphs, and Subparagraphs are for ease of reference only and will not in any way affect or be used in interpreting any of the provisions of these Terms. Unless the context otherwise requires, a reference to a Section, Subsection, Paragraph, Subparagraph or Schedule by number or letter is a reference to the appropriate Section, Subsection, Paragraph, Subparagraph or Schedule in these Terms. In these Terms, the singular of any term includes the plural and vice versa and the use of any term is equally applicable to any gender and where applicable to a corporate entity; and the conjunction “or” will be understood in its inclusive sense (and/or).</li>
        </ol>
    </ContentBox>
   <MoreQuestion mt={5} />
   <Footer/>
</main>
    )
}

export default TermsAndConditions

