const Route = {
  HOME: "/",
  FEATURE: "/feature",
  PRICING: "/pricing",
  DEVELOPER: "/developer",
  HELP: "/help",
  LOGIN: "/login",
  SIGNUP: "/signup",
  TERM_CONDITION: "/term&condition",
  CONTACT_US: "/contactUs",
  COOKIE_POLICY: "/cookiePolicy",
  PRIVACY_POLICY: "/privacyPolicy",
  BLOGS: "/blogs",
  EXTENDED_BLOGS: "/blogExtended",
  FEATURE_PAGES: "/features",
  IN_PERSON:"/features?feature=In-Person-Signing",
  TEMPLATES:"/features?feature=Templates",
  SECURITY:"/features?feature=Document-Management-&-Security",
  SANDBOX_SIGNUP: "/sandbox",
  SANDBOX_ACCOUNT: "/sandbox/sandAccount",
  SANDBOX_ACCOUNT_API: "/sandbox/sandAccountApi",
  SANDBOX_BUSINESS: "/sandbox/sandBusiness",
  API_DOCUMENTATION: "/APIDocumentation",
  ELECTRONIC_SIGNATURES:"/features?feature=Electronic-Signatures",
 DOCUMENT_EDITOR:"/features?feature=Document-Editor",
 AUDIT_TRAIL:"/features?feature=Audit-Trail",
APP_INTEGRATION:"/features?feature=Integration",

  // Dashboard routes
  DASHBOARD: "/dashboard",
  DOCUMENT: "/documents",
  TEMPLATE: "/templates",
  CONTACT: "/contacts",
  TEAM: "/teams",
  TRASH: "/trash",
  SETTINGS: "/settings",
  NEW_CONTACT: "/contacts/newContact",
  NEW_TEAM_MEMBER: "/newTeamMember",
  NEW_DOCUMENT: "/newDocument",
  NEW_TEMPLATE: "/newTemplate",
  GENERAL_PREFERENCES: "/generalPreferences",
};

export default Route;